# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - build
  - deploy
sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

build_kaniko_command:
  stage: build
  variables:
    IMAGE_DESTINATION: ${CI_REGISTRY_IMAGE}:latest
  image:
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_DESTINATION --build-arg TMWS_REPO_SECRET=$TMWS_REPO_KEY --build-arg GITLAB_USER=gitlab-ci-token --build-arg GITLAB_TOKEN=$CI_JOB_TOKEN
    - echo "Image pushed successfully to ${IMAGE_DESTINATION}"

update_imagestream_and_redeploy: 
  stage: deploy 
  image: gitlab-registry.cern.ch/paas-tools/openshift-client:latest 
  variables: 
    SERVER: https://api.paas.okd.cern.ch 
    PROJECT: te-msc-tm   # name of your Openshift project 
    APP_NAME: sps-database-web-interface  # name of the ImageStream/DeploymentConfig objects created by oc new-app 
  script: 
  - oc login $SERVER --token=$DEPLOY_TOKEN 
  - oc project $PROJECT 
  - oc import-image $APP_NAME --all 
  - sleep 10 && oc rollout status deployment/$APP_NAME 
